export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const CURRENT_USER = "CURRENT_USER";

export const AUTH_LOADING = "AUTH_LOADING";
export const LOGIN_SUCCEED = "LOGIN_SUCCEED";
export const LOGOUT_SUCCEED = "LOGOUT_SUCCEED";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LEVELS_LOADING = "LEVELS_LOADING";
export const FETCH_LEVELS_SUCCEED = "FETCH_LEVELS_SUCCEED";
export const FETCH_LEVELS_FAILED = "FETCH_LEVELS_FAILED";
export const ADD_NEW_LEVEL = "ADD_NEW_LEVEL";

export const SUBJECT_LOADING = "SUBJECT_LOADING";
export const FETCH_SUBJECT_SUCCEED = "FETCH_SUBJECT_SUCCEED";
export const FETCH_SUBJECT_FAILED = "FETCH_SUBJECT_FAILED";
export const ADD_NEW_SUBJECT = "ADD_NEW_SUBJECT";

export const SUBJECT_CONTENT_LOADING = "SUBJECT_CONTENT_LOADING";
export const FETCH_SUBJECT_CONTENT_SUCCEED = "FETCH_SUBJECT_CONTENT_SUCCEED";
export const FETCH_SUBJECT_CONTENT_FAILED = "FETCH_SUBJECT_CONTENT_FAILED";
export const ADD_NEW_SUBJECT_CONTENT = "ADD_NEW_SUBJECT_CONTENT";
